# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai-docs-gpt',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/fastai-docs-gpt',
                'lib_path': 'fastai_docs_gpt'},
  'syms': {'fastai_docs_gpt.core': {'fastai_docs_gpt.core.foo': ('core.html#foo', 'fastai_docs_gpt/core.py')}}}
